server:
  port: '8080'
  compression:
    enabled: 'true'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.56.101:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    password: '123456'
  flyway:
    ignore-migration-patterns: V5__.*,V6__.*,V10__.*
    enabled: false
    clean-disabled: true
  profiles:
    active: prod
  main:
    allow-circular-references: 'true'
    jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm
    web:
      resources:
        chain:
          compressed: 'true'
    servlet:
      multipart:
        max-file-size: '-1'
        max-request-size: '-1'
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
zfile:
  log:
    path: ${user.home}/.zfile-v4/logs
    encoder: UTF-8
  db:
    path: ${user.home}/.zfile-v4/db/zfile
  preview:
    text:
      maxFileSizeKb: '512'
  debug: 'false'
  onedrive:
    scope: offline_access User.Read Files.ReadWrite.All Sites.Read.All Sites.ReadWrite.All
    clientId: 09939809-c617-43c8-a220-a93c1513c5d4
    clientSecret: _l:zI-_yrW75lV8M61K@z.I2K@B/On6Q
    redirectUri: https://zfile.jun6.net/onedrive/callback
  onedrive-china:
    scope: offline_access User.Read Files.ReadWrite.All Sites.Read.All Sites.ReadWrite.All
    clientSecret: Y9CEA=82da5n-y_]KAWAgLH3?R9xf7Uw
    clientId: 4a72d927-1907-488d-9eb2-1b465c53c1c5
    redirectUri: https://zfile.jun6.net/onedrive/china-callback
  gd:
    redirectUri: http://localhost:8080/gd/callback
    clientId: 659016983345-vlp413rgrl2spe5d53ml16p2btslfa44.apps.googleusercontent.com
    clientSecret: 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
    scope: https://www.googleapis.com/auth/drive
sa-token:
  is-print: 'false'
  token-name: zfile-token
knife4j:
  enable: 'true'
  setting:
    enableSwaggerModels: 'true'
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: 'true'

logging:
  config: classpath:log4j2-spring.xml
